---
author: Connor Aird
institute: University College London
date: 2026-01-31
format: revealjs
subtitle: "ARC Forum"
title: Pytest Benchmark, was it worth it?
logo: /assets/ucl_logo_light.png
recording:
---

{{< include _slides/re-intro.qmd >}}

{{< include _slides/project-context.qmd >}}

{{< include _slides/what-is-pytest-benchmark.qmd >}}

# How we used pytest-benchmark

## How we used pytest-benchmark

#### Overview

::: {.r-fit-text}

- Define benchmark tests within the same repo as core-tests and src code.
- Reuse fixtures from core-tests.
- Minimise assertions to avoid flakiness.
- Define Regression tests which compare BASE ref to HEAD ref for PRs.
  - Benchmark tests are defined in the HEAD ref.
  - Run in GitHub actions.
  - Both runs occur right after one another so in theory experince the same load
    on the machine.

:::

## Workflow

Example workflow from GLASS

```yaml {code-line-numbers="5-19|20-32|61-67"}
{ { < include _code/regression_test_Workflow.yaml > } }
```

## How we used pytest-benchmark

#### issues

- If the GLASS api changed (i.e. new module) the regression tests would fail.
- Many false positives, we think - i.e. flaky.
  - Split benchmark-tests into stable and unstable.
    - Different regression test metrics.
  - Maximise problem size.
  - Filter to only run for NumPy.

# Conclusion

- Has definitely highlighted regressions.
- Not clear if it was worth it.
- We hope to use it in the future for…
  - Demonstrating GPU improvements.
  - Benchmarking on different machines.
